# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # checkout
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    # deploy
    - name: Deploy
      uses: easingthemes/ssh-deploy@v2.0.9
      env:
        REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
        REMOTE_USER: ${{ secrets.REMOTE_USER }}
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        TARGET: ${{ secrets.TARGET }}
        ARGS: "-avzt"
        SOURCE: "_book/"
  
    # update serverfiles
    - name: updateServerfiles
      uses: appleboy/ssh-action@v0.0.7
      with:
        host: ${{ secrets.REMOTE_HOST }}
        username: ${{ secrets.REMOTE_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          cd ${{ secrets.TARGET }}
          git add .
          git commit -m "更新d3布局算法相关文件"
          git push github master